### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by samuong** [samuong/alpaca#11]
Alpaca releases should be given a version number and this version should be made visible via a `-version` flag and/or printed in the logs.

There is currently no concept of a "release" in Alpaca, so resolving this issue would require a build/release pipeline to be set up.

**Comment by rtfmoz2** [comment]
git describe --tags | head -1 will give you latest release tag on the current cloned repo. If you are using macos you can get the version number with the following variable substitution in KSH.
```
VER=`git describe --tags | head -1`
VER=${VER#v}
VER=${VER%-*-*}
```

**Comment by rtfmoz2** [comment]
I think this indicates that versioning is happening around go modules automatically without there being explicit code - https://go.dev/blog/publishing-go-modules

**Comment by rtfmoz2** [comment]
Got a solution, adding a commit soon

**Comment by rtfmoz2** [comment]
https://github.com/samuong/alpaca/pull/78
