### ISSUE TITLE
The myIpAddress() function returns an unexpected IP address

### ISSUE THREAD

**Issue by samuong** [samuong/alpaca#122]
The current implementation of [myIpAddress()](https://github.com/samuong/alpaca/blob/99af862800f190ecc83bb5d06db80b080f173d60/pacrunner.go#L184) iterates over the list of interface addresses from [net.InterfaceAddrs()](https://pkg.go.dev/net#InterfaceAddrs), skipping over any IPv6 addresses, and IPv4 loopback addresses. Otherwise it returns the first IP address that it finds.

For example, a laptop's WiFi adapter might have an IP address of 192.168.1.2, but when connected to my corporate VPN, it will _also_ have a network interface with the address 10.1.2.3. In many cases, Alpaca's implementation of myIpAddress() will pick the first address, which is not the internet-bound address, and not what many PAC scripts expect.

Alpaca is also inconsistent with the approaches taken by other implementations like [Chrome](https://chromium.googlesource.com/chromium/src/+/ee43fa5328856129f46566b2ea1be5811739681c/net/docs/proxy.md#Resolving-client_s-IP-address-within-a-PAC-script-using-myIpAddress) and [Firefox](https://hg.mozilla.org/mozilla-central/file/76bd539d488655f87df335ca2462d9a4fc4c1d6d/netwerk/base/ProxyAutoConfig.cpp#l790). We should align on either of these approaches, or at least do something similar.

**Comment by ziyiwang** [comment]
yup, confirmes this is working as expected on ourside, its now picking up the internet bound IP.
