### ISSUE TITLE
alpaca 2.0.5 killed on start on MacOS 14.5 (23F79) arm64

### ISSUE THREAD

**Issue by mdemierre** [samuong/alpaca#128]
Since the upgrade to 2.0.5 I'm unable to start alpaca.

I tried both the brew version and to directly run the binary downloaded from GitHub.

When starting the binary I get this:

```
./alpaca_v2.0.5_darwin-arm64
[1]    3264 killed     ./alpaca_v2.0.5_darwin-arm64
```

I also get a popup saying:

```
“alpaca_v2.0.5_darwin-arm64” is damaged and can’t be opened. You should move it to the Trash.
```

If I try the brew service I get:

```
alpaca        error  9 <username> ~/Library/LaunchAgents/homebrew.mxcl.alpaca.plist
```

If I try the binary of the older version I get a different popup about unrecognized signature, and then I can accept it through the Preferences in Privacy & Security. For 2.0.5 I get nothing there.

Installing alpaca via Go works, I believe 

Was anything changed in the signing or build process between 2.0.4 and 2.0.5?

**Comment by mike-a-bike** [comment]
Same issue here. Immediately killed process after update to 2.0.5 via Homebrew.
OS Version: 14.5 (23F79)
CPU: Apple M3 Pro (arm64)
Credential Config: Kerberos

Downgraded to 2.0.4, works like a charm.

**Comment by samuong** [comment]
Thanks for reporting this. I can reproduce it locally on my MacBook Pro.

There was a change with the build process in v2.0.5, which was that the Go version on the runners was upgraded to 1.22. I suspect this has something to do with it, although I'm not sure exactly how. Strangely, I can build and run the binary just fine if I build it on my own laptop. I'm not sure how the GHA runners differ, but I'll look into this.

**Comment by samuong** [comment]
Ok I've bumped a few versions in the workflow, and that seems to fix it. I'll release this as v2.0.6 shortly.

**Comment by samuong** [comment]
Oops, I fixed the CI workflow, but not the release workflow, so v2.0.6 went out broken in the same way! I've just reapplied the fix to the release workflow and pushed this out as v2.0.7. I've also updated the Homebrew tap so you should be able to update this via brew.

Please let me know if anything is still broken, and thanks again for reporting!

**Comment by mike-a-bike** [comment]
Thank you for fixing this so soon. Much appreciated! 👍 
**And thank you for this project and your work.**

It works like a charm!

**Comment by mdemierre** [comment]
@samuong Thanks for the quick fix! Also works fine on my environment now with the latest binaries.
