### ISSUE TITLE
Connect timeout blocks all connections

### ISSUE THREAD

**Issue by chrisgavinator** [samuong/alpaca#54]
Seeing a few of these...

2020/06/10 15:46:48 proxy.go:146: [16301] Error reading CONNECT response: read tcp xx.xx.xx.xx:xxxx->xx.xx.xx.xx:xxxx: read: operation timed out

They appear to block all other connections through alpaca when they occur.

**Comment by camh-** [comment]
It is possible that if one connection to the proxy is timing out, the proxy is generally unresponsive. This would look like the other connections are blocked too. Does traffic immediately return after this point in the logs?

**Comment by samuong** [comment]
Closing this as it appears to have been an issue with the upstream proxy, that has been fixed. Feel free to reopen if it starts to cause problems again.
