### ISSUE TITLE
MacOS deprecating APIs in go-keychain

### ISSUE THREAD

**Issue by keilin-anz** [samuong/alpaca#68]
_(NB: Just a note for now, as I've not got a machine running Big Sur to do any testing)_

## Overview

Seems one of the ABIs used by `go-keychain` has been recently deprecated - it presumedly still works (with warnings), but that likely won't last long:

(copied from another user)
```
~ % go get -v github.com/samuong/alpaca
# github.com/keybase/go-keychain
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
```

Also see: https://github.com/keybase/go-keychain/issues/54

## What to do?

Hopefully just bump the `go-keychain` version, assuming they've worked out how to transparently support the older OS ABI alongside the new one

**Comment by samuong** [comment]
Hi @keilin-anz, thanks for the heads up. I was able to repro this on my MacBook Pro, which is running Big Sur.

I was also able to make it go way by bumping the `go-keychain` version (which I did in 3610028 as part of another change). If you run `go get -v github.com/samuong/alpaca@3610028` and still get the error, let me know?

**Comment by keilin-anz** [comment]
Glad to hear bumping worked well for you, will confirm it doesn't break functionality on older OS and update here soon

**Comment by samuong** [comment]
Btw I just remembered that this was actually fixed in an earlier commit than 3610028; see #60. I think we can close this, but feel free to reopen if you continue to see it.

**Comment by samhaque** [comment]
This issue resurfaced in macOS Monterey (12.3.0), could you bump up the version again @samuong ?

**Comment by samhaque** [comment]
Here is the screenshot![image](https://user-images.githubusercontent.com/13789262/163908160-1ee16871-5db0-4878-80e4-b2d0c122dc6e.png)

**Comment by samuong** [comment]
Unfortunately, bumping the version won't fix it this time; Apple have removed the deprecated API and we'll have to stop using it.

We use custom keychain management for testing purposes in Alpaca, so I can remove this without changing any functionality, but test coverage will drop as a result. I'll have a go at putting together a PR for this tonight.
