### ISSUE TITLE
Add Apple 64bit architecture support to brew tap

### ISSUE THREAD

**Issue by samhaque** [samuong/alpaca#84]
I noticed that Apple silicon running on ARM64 is not a release target in the brew tap, is it possible to add a if statement in the brew tap script to support:
`GOOS=darwin GOARCH=arm64 go build`?

**Comment by samhaque** [comment]
Pushed a PR to fix this: https://github.com/samuong/homebrew-alpaca/pull/1

**Comment by samhaque** [comment]
@samuong @rtfmoz2 if you get a chance please review this PR.

**Comment by samuong** [comment]
Thanks for this @samhaque, I've just approved and merged it.
