### ISSUE TITLE
failed to parse the pac file and obtain the proxy

### ISSUE THREAD

**Issue by xueliang** [samuong/alpaca#92]
The pac works in my chrome, but in alpaca, the log shows that :

 proxyfinder.go:128: [1] Couldn't parse proxy: "HTTPS ssl-xxxxxx.yyyyy.com:3389"

Is there anything wrong? Thanks.

**Comment by samuong** [comment]
The [original return value format from Netscape](https://web.archive.org/web/20070602031929/http://wp.netscape.com/eng/mozilla/2.0/relnotes/demo/proxy-live.html) for PAC scripts only supported values that started with `DIRECT` or `PROXY` (or `SOCKS`, which Alpaca doesn't support). [Newer versions of Firefox](https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file#return_value_format), as well as other browsers like [Chrome](https://chromium.googlesource.com/chromium/src/+/HEAD/net/docs/proxy.md#proxy-server-schemes), later added `HTTP` and `HTTPS`.

Alpaca was written against the older standard, and only supports `DIRECT` and `PROXY`. But it's easy enough to add `HTTP` and `HTTPS`, which should fix your problem.
